import { colorModeContext, useMode } from './theme'
import { CssBaseline, ThemeProvider } from '@mui/material'
import './globals.css'
import Topbar from '@/scenes/Topbar'

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [theme, colorMode]= useMode()

  return (
    <html lang="en">
      <body className={inter.className}>
        <colorModeContext.Provider value={colorMode}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <div className='app'>
              <main className='content'>
                <Topbar />
                {children}
              </main>
            </div>
          </ThemeProvider>
        </colorModeContext.Provider>
        </body>
    </html>
  )
}
